
'use server';

import { db } from "@/lib/firebase";
import { doc, runTransaction, FieldValue, collection, getDocs, writeBatch } from "firebase/firestore";
import type { InventoryMovement, DailyMovementLog } from "@/lib/types";
import { format } from "date-fns";

// Utility to generate a unique ID for each movement event
function generateEventId(): string {
  return `${Date.now().toString()}-${Math.random().toString(36).substring(2, 9)}`;
}

interface LogMovementData extends Omit<InventoryMovement, 'eventId' | 'recordedAt'> {
  // eventId and recordedAt will be generated by the service
}

export async function logInventoryMovement(movementData: LogMovementData): Promise<void> {
  const todayStr = format(new Date(), "yyyy-MM-dd"); // Use movementDate from data if present, else today
  const docIdDate = movementData.movementDate || todayStr;
  const dailyLogDocRef = doc(db, "dailyMovementLogs", docIdDate);
  const currentTimestamp = new Date().toISOString();

  const newMovementEvent: InventoryMovement = {
    ...movementData,
    eventId: generateEventId(),
    recordedAt: currentTimestamp,
    movementDate: movementData.movementDate || todayStr, // Ensure movementDate is set in the event itself
  };

  try {
    await runTransaction(db, async (transaction) => {
      const dailyLogDoc = await transaction.get(dailyLogDocRef);

      if (!dailyLogDoc.exists()) {
        // Create new daily log document
        const newDailyLog: DailyMovementLog = {
          id: docIdDate,
          date: docIdDate,
          movements: [newMovementEvent],
          lastUpdated: currentTimestamp,
        };
        transaction.set(dailyLogDocRef, newDailyLog);
      } else {
        // Append to existing daily log document
        transaction.update(dailyLogDocRef, {
          movements: FieldValue.arrayUnion(newMovementEvent),
          lastUpdated: currentTimestamp,
        });
      }
    });
  } catch (error: any) {
    const originalErrorMessage = error.message || "Unknown error during Firestore transaction";
    console.error("Error logging inventory movement: Original error ->", error);
    // throw new Error("Failed to log inventory movement."); // Original line
    throw new Error(`Failed to log inventory movement: ${originalErrorMessage}`); // Modified line
  }
}

export async function clearAllDailyMovementLogs(): Promise<{ success: boolean; message: string }> {
  const dailyLogsCollectionRef = collection(db, "dailyMovementLogs");
  try {
    const querySnapshot = await getDocs(dailyLogsCollectionRef);
    if (querySnapshot.empty) {
      return { success: true, message: "No logs found to delete." };
    }

    const batchSize = 400; 
    let batch = writeBatch(db);
    let count = 0;

    for (const docSnapshot of querySnapshot.docs) {
      batch.delete(docSnapshot.ref);
      count++;
      if (count === batchSize) {
        await batch.commit();
        batch = writeBatch(db); 
        count = 0;
      }
    }

    if (count > 0) {
      await batch.commit();
    }

    return { success: true, message: "All inventory movement logs have been successfully deleted." };
  } catch (error: any) {
    console.error("Error clearing all daily movement logs: ", error);
    return { success: false, message: `Failed to clear logs: ${error.message || "Unknown error"}` };
  }
}
